# Generated by Django 4.0.4 on 2022-05-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='StuartOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('order_number', models.IntegerField(max_length=4)),
                ('order_fee', models.FloatField()),
                ('order_multiplier', models.FloatField()),
                ('order_total', models.FloatField()),
                ('rest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersInfoApp.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Stuart Orders',
            },
        ),
        migrations.CreateModel(
            name='DeliverooOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('order_number', models.IntegerField(max_length=4)),
                ('order_fee', models.FloatField()),
                ('order_tip', models.FloatField()),
                ('order_total', models.FloatField()),
                ('rest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersInfoApp.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Deliveroo Orders',
            },
        ),
    ]
