# Generated by Django 4.0.4 on 2022-06-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersInfoApp', '0002_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverooorders',
            name='order_total',
        ),
    ]
