# Generated by Django 4.0.4 on 2022-06-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersInfoApp', '0003_remove_deliverooorders_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuartorders',
            name='order_total',
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='finish_time',
            field=models.DateTimeField(blank=True, help_text='Enter the finish time of the order'),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='order_fee',
            field=models.FloatField(help_text="Enter the order fee (e.g. '3.15')"),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='order_number',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the order number'),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='order_tip',
            field=models.FloatField(help_text="Enter the order tip (e.g. '1.00')"),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='rest_name',
            field=models.ForeignKey(help_text='Select a Restaurant', on_delete=django.db.models.deletion.CASCADE, to='OrdersInfoApp.restaurant'),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter the start time of the order'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text="Enter a restaurant name (e.g. 'PizzaHut')", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stuartorders',
            name='order_fee',
            field=models.FloatField(help_text="Enter the order fee (e.g. '4.50')"),
        ),
        migrations.AlterField(
            model_name='stuartorders',
            name='order_multiplier',
            field=models.FloatField(help_text="Enter the order multiplier (e.g. '2.10')"),
        ),
        migrations.AlterField(
            model_name='stuartorders',
            name='order_number',
            field=models.IntegerField(blank=True, help_text='Enter the order number (last 4 digits)'),
        ),
        migrations.AlterField(
            model_name='stuartorders',
            name='order_time',
            field=models.DateTimeField(blank=True, help_text='Enter the order time'),
        ),
        migrations.AlterField(
            model_name='stuartorders',
            name='rest_name',
            field=models.ForeignKey(help_text='Select a Restaurant', on_delete=django.db.models.deletion.CASCADE, to='OrdersInfoApp.restaurant'),
        ),
    ]
