# Generated by Django 4.0.4 on 2022-06-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersInfoApp', '0004_remove_stuartorders_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverooorders',
            name='finish_time',
            field=models.DateTimeField(help_text='Enter the finish time of the order'),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='order_number',
            field=models.IntegerField(default=0, help_text='Enter the order number'),
        ),
        migrations.AlterField(
            model_name='deliverooorders',
            name='start_time',
            field=models.DateTimeField(help_text='Enter the start time of the order'),
        ),
    ]
