# Generated by Django 4.0.4 on 2022-06-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersInfoApp', '0005_alter_deliverooorders_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverooorders',
            options={'ordering': ['-rest_name'], 'verbose_name_plural': 'Deliveroo Orders'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Restaurants'},
        ),
    ]
